# Generated by Django 2.1.3 on 2018-12-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photos',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
