# Generated by Django 2.1.3 on 2018-12-03 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chidog_api', '0004_auto_20181202_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
