# Generated by Django 2.1.3 on 2018-12-04 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pet_photo', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=1)),
                ('likes_people', models.CharField(default='Likes People?', max_length=100)),
                ('likes_dogs', models.CharField(default='Likes Dogs?', max_length=100)),
                ('loves_to', models.CharField(default='Loves To?', max_length=100)),
                ('fav_treat', models.CharField(default='Favorite Treat?', max_length=100)),
                ('vet_name', models.CharField(default='Vet Name', max_length=100)),
                ('vet_phone', models.IntegerField(default=0)),
                ('vet_address', models.TextField(default='Vet Address')),
                ('fixed', models.CharField(default='Spayed/Neutered?', max_length=100)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_body', models.TextField()),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_body', models.TextField()),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('replied_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chidog_api.Post')),
            ],
        ),
    ]
