# Generated by Django 2.1.3 on 2018-12-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chidog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='fav_treat',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='fixed',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='likes_dogs',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='likes_people',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='loves_to',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vet_address',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vet_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
