# Generated by Django 2.1.3 on 2018-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chidog_api', '0002_auto_20181204_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vet_phone',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
